"""user contacts and team descs

Revision ID: 00bbab3ccf6f
Revises: e7b7d93cdb01
Create Date: 2024-05-26 23:19:53.372226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session, Mapped, mapped_column
from sqlalchemy import select, inspect
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()



# revision identifiers, used by Alembic.
revision: str = '00bbab3ccf6f'
down_revision: Union[str, None] = 'e7b7d93cdb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class Team(Base):
    __tablename__ = 'teams'
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(unique=True, nullable=False)
    team_description: Mapped[str] = mapped_column(nullable=False)
    search_user_description: Mapped[str] = mapped_column(nullable=False)


def upgrade() -> None:
    bind = op.get_bind()
    insp = inspect(bind)
    team_columns = insp.get_columns('teams')
    user_columns = insp.get_columns('users')
    if any(c["name"] in ['team_description', 'search_user_description'] for c in team_columns) or any(c["name"] in ['vk', 'github', 'telegram'] for c in user_columns):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('team_description', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('search_user_description', sa.String(), nullable=True))
    op.drop_column('teams', 'description')
    op.add_column('users', sa.Column('vk', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram', sa.String(), nullable=True))
    op.drop_column('users', 'сontact')
    # ### end Alembic commands ###

    session = Session(bind=bind)
    teams = session.execute(select(Team)).scalars().all()
    for team in teams:
        team.team_description = 'пусто'
        team.search_user_description = 'пусто'
    session.commit()
    op.alter_column('teams', 'team_description', nullable=False)
    op.alter_column('teams', 'search_user_description', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('сontact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'telegram')
    op.drop_column('users', 'github')
    op.drop_column('users', 'vk')
    op.add_column('teams', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('teams', 'search_user_description')
    op.drop_column('teams', 'team_description')
    # ### end Alembic commands ###
