"""contacts

Revision ID: e7b7d93cdb01
Revises: 
Create Date: 2024-05-26 17:29:42.387618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.db_setup import Base


# revision identifiers, used by Alembic.
revision: str = 'e7b7d93cdb01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
conn = op.get_bind()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('users', sa.Column('сontact', sa.String(), nullable=True))
    Base.metadata.create_all(conn.engine)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
